sudo: false
language: perl
matrix:
    fast_finish: true
perl:
    - "5.22"
    - "5.20"
    - "5.18"
    - "5.16"
    - "5.14"
    - "5.12"
    - "5.10"
before_install:
    - "cpanm ."
    - "cpanm -qn Test::Requires::Git"
    - "cpanm -qn Devel::Cover::Report::Codecov"
script:
    perl Makefile.PL && make test
after_success:
    cover -test -report codecov
